### PR TITLE
update to new records in cosas

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by laughedelic** [comment]
:+1: this is also a good test for what's missing there

**Comment by eparejatobes** [comment]
I'm going to
- [ ] make all options properties
- [ ] Arguments a record, one for each command

Now, what about options? should a record be required there too?

**Comment by eparejatobes** [comment]
The only kinda controversial part was what to do with the `toSeq` method; I discussed this with @laughedelic and we have agreed on mapFolding/whatever over the corresponding typeset of ValuesOf

**Comment by eparejatobes** [comment]
will finish this tomorrow, what's left is just a matter of code reorganization.

**Comment by eparejatobes** [comment]
Everything is way easier if every command has a fixed set of options, declared beforehand as a record. We can add defaults and update them, but this is a must. Otherwise the types get really ugly and everything's harder to understand

**Comment by eparejatobes** [comment]
LGTM

**Pull request merged**
